name: fuoday
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # screen util
  flutter_screenutil: ^5.9.3

  # state management
  provider: ^6.1.5

  # router
  go_router: ^16.0.0

  # flutter svg
  flutter_svg: ^2.2.0

  # pin input
  pinput: ^5.0.1

  # dio
  dio: ^5.8.0+1

  # logger
  logger: ^2.6.0

  # pretty dio logger
  pretty_dio_logger: ^1.4.0

  # hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # flutter secure storage
  flutter_secure_storage: ^9.2.4

  # di
  get_it: ^8.0.3

  # google fonts
  google_fonts: ^6.2.1

  # cached_network_image:
  cached_network_image:

  # stop watch timer
  stop_watch_timer: ^3.2.2

  # intl
  intl: ^0.20.2

  # Data Table
  data_table_2: ^2.6.0

  # carousel_slider:
  carousel_slider: ^5.1.1

  # smooth page indicator
  smooth_page_indicator: ^1.2.1

  # flutter expandable fab
  flutter_expandable_fab: ^2.5.2

  # fl chart
  fl_chart: ^1.0.0

  # month picker dialog
  month_picker_dialog: ^6.3.0

  # drop down button 2
  dropdown_button2: ^2.3.9

  # dotted border
  dotted_border: ^3.1.0

  # graph view
  graphview: ^1.2.0

  # syncfusion_flutter_calendar
  syncfusion_flutter_calendar: ^30.1.39

  # flutter rating bar
  flutter_rating_bar: ^4.0.1

  #file_picker:
  file_picker: ^10.2.0

  # pdf viewer
  syncfusion_flutter_pdfviewer: ^30.1.40

  # image viewer
  easy_image_viewer: ^1.5.1

  # image picker
  image_picker: ^1.1.2

  # path provider
  path_provider: ^2.1.5

  # permission_handler
  permission_handler: ^12.0.1

  # flutter file downloader
  flutter_file_downloader: ^2.1.0

  # open fileX
  open_filex: ^4.7.0

  # flutter_dotenv
  flutter_dotenv: ^5.2.1

  #dartx:
  dartz: ^0.10.1

  # printing pdf
  printing: ^5.14.2

  # pdf
  pdf: ^3.11.3

  # excel
  excel: ^4.0.6

  # connectivity_plus:
  connectivity_plus: ^6.1.4

  #equatable:
  equatable: ^2.0.7

  #url_launcher:
  url_launcher: ^6.3.0

  #page_transition:
  page_transition: ^2.1.0

  #firebase_core:
  firebase_core: ^4.0.0

  #pie_chart:
  pie_chart: ^5.3.2






dependency_overrides:
  source_gen: ^3.0.0
  build: ^3.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  #change_app_package_name:
  change_app_package_name: ^1.5.0

  # build runner
  build_runner: ^2.6.0

  #flutter_launcher_icons:
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true


  assets:
    #Icons Svg
    - assets/icons/
    # svg
    - assets/images/svg/
    # png
    - assets/images/png/
    # jpg
    - assets/images/jpg/
    # env
    - .env


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/png/Fuoday_logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
